name: Publish

on:
  workflow_dispatch:
  push:
   paths-ignore:
     - '.gitignore'
     - 'CONTRIBUTING.md'
     - 'LICENSE'
     - 'README.md'
     - 'licenseheader.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@72f2cec99f417b1a1c5e2e88945068983b7965f9
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4
      - uses: actions/setup-java@4075bfc1b51bf22876335ae1cd589602d60d8758
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Publish to Modrinth
        uses: gradle/gradle-build-action@3bfe3a46584a206fb8361cdedd0647b0c4204232
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        with:
          arguments: modrinth
          gradle-home-cache-cleanup: true
      - name: Archive Artifacts (fabric)
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        if: success()
        with:
          name: Hurricane Fabric
          path: fabric/build/libs/hurricane-fabric.jar
          if-no-files-found: error
      - name: Archive Artifacts (neoforge)
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        if: success()
        with:
          name: Hurricane NeoForge
          path: neoforge/build/libs/hurricane-neoforge.jar
          if-no-files-found: error